from django.urls import path
from . import views

urlpatterns = [
    path("", views.conversion_dashboard, name="conversion_dashboard"),
    path("length_converter/", views.length_converter, name="length_converter"),
    path("weight_mass_converter/", views.weight_mass_converter, name="weight_mass_converter"),
    path("volume_converter/", views.volume_converter, name="volume_converter"),
    path("area_converter/", views.area_converter, name="area_converter"),
    path("temperature_converter/", views.temperature_converter, name="temperature_converter"),
    path("speed_converter/", views.speed_converter, name="speed_converter"),
    path("pressure_converter/", views.pressure_converter, name="pressure_converter"),
    path("energy_converter/", views.energy_converter, name="energy_converter"),
    path("power_converter/", views.power_converter, name="power_converter"),
    path("data_storage_converter/", views.data_storage_converter, name="data_storage_converter"),
    path("time_zone_converter/", views.time_zone_converter, name="time_zone_converter"),
    path("cooking_measurement_converter/", views.cooking_measurement_converter, name="cooking_measurement_converter"),
    path("shoe_size_converter/", views.shoe_size_converter, name="shoe_size_converter"),
    path("clothing_size_converter/", views.clothing_size_converter, name="clothing_size_converter"),
    path("angle_converter/", views.angle_converter, name="angle_converter"),
    path("fuel_consumption_converter/", views.fuel_consumption_converter, name="fuel_consumption_converter"),
    path("digital_image_resolution_converter/", views.digital_image_resolution_converter, name="digital_image_resolution_converter"),
    path("lumber_board_foot_calculator/", views.lumber_board_foot_calculator, name="lumber_board_foot_calculator"),
    path("ring_size_converter/", views.ring_size_converter, name="ring_size_converter"),
    path("number_system_converter/", views.number_system_converter, name="number_system_converter"),
    path("roman_numeral_converter/", views.roman_numeral_converter, name="roman_numeral_converter"),
    path("morse_code_converter/", views.morse_code_converter, name="morse_code_converter"),
    path("braille_converter/", views.braille_converter, name="braille_converter"),
    path("password_generator_calculator/", views.password_generator_calculator, name="password_generator_calculator"),
    path("cryptographic_hash_generator/", views.cryptographic_hash_generator, name="cryptographic_hash_generator"),
    path("color_code_converter/", views.color_code_converter, name="color_code_converter"),
    path("electric_charge_converter/", views.electric_charge_converter, name="electric_charge_converter"),
    path("radiation_dose_converter/", views.radiation_dose_converter, name="radiation_dose_converter"),
    path("viscosity_converter/", views.viscosity_converter, name="viscosity_converter"),
    path("flow_rate_converter/", views.flow_rate_converter, name="flow_rate_converter"),
    path("torque_converter/", views.torque_converter, name="torque_converter"),
    path("density_converter/", views.density_converter, name="density_converter"),
    path("surface_tension_converter/", views.surface_tension_converter, name="surface_tension_converter"),
    path("catalytic_activity_converter/", views.catalytic_activity_converter, name="catalytic_activity_converter"),
    path("luminous_intensity_converter/", views.luminous_intensity_converter, name="luminous_intensity_converter"),
    path("radioactivity_converter/", views.radioactivity_converter, name="radioactivity_converter"),
    path("acceleration_converter/", views.acceleration_converter, name="acceleration_converter"),
    path("force_converter/", views.force_converter, name="force_converter"),
    path("moment_of_inertia_converter/", views.moment_of_inertia_converter, name="moment_of_inertia_converter"),
    path("metric_prefix_converter/", views.metric_prefix_converter, name="metric_prefix_converter"),
    path("typography_unit_converter/", views.typography_unit_converter, name="typography_unit_converter"),
    path("audio_conversion_calculator/", views.audio_conversion_calculator, name="audio_conversion_calculator"),
    path("video_file_size_calculator/", views.video_file_size_calculator, name="video_file_size_calculator"),
    path("screen_aspect_ratio_calculator/", views.screen_aspect_ratio_calculator, name="screen_aspect_ratio_calculator"),
    path("map_scale_calculator/", views.map_scale_calculator, name="map_scale_calculator"),
    path("earthquake_magnitude_scale_calculator/", views.earthquake_magnitude_scale_calculator, name="earthquake_magnitude_scale_calculator"),
    path("hurricane_speed_calculator/", views.hurricane_speed_calculator, name="hurricane_speed_calculator"),
    path("ph_to_hydrogen_ion_concentration_converter/", views.ph_to_hydrogen_ion_concentration_converter, name="ph_to_hydrogen_ion_concentration_converter"),
    path("blood_sugar_unit_converter/", views.blood_sugar_unit_converter, name="blood_sugar_unit_converter"),

]