from django.urls import path
from . import views

urlpatterns = [
    path("", views.date_time_home, name="date_time_dashboard"),

    path('date_difference_calculator/', views.date_difference_calculator, name='date_difference_calculator'),
    path('date_addition_and_subtraction_calculator/', views.date_addition_and_subtraction_calculator, name='date_addition_and_subtraction_calculator'),
    path('day_of_the_week_calculator/', views.day_of_the_week_calculator, name='day_of_the_week_calculator'),
    path('age_calculator/', views.age_calculator, name='age_calculator'),
    path('business_days_calculator/', views.business_days_calculator, name='business_days_calculator'),
    path('time_duration_calculator/', views.time_duration_calculator, name='time_duration_calculator'),
    path('time_zone_converter/', views.time_zone_converter, name='time_zone_converter'),
    path('world_clock_meeting_planner/', views.world_clock_meeting_planner, name='world_clock_meeting_planner'),
    path('custom_countdown_timer/', views.custom_countdown_timer, name='custom_countdown_timer'),
    path('digital_stopwatch/', views.digital_stopwatch, name='digital_stopwatch'),
    path('anniversary_and_milestone_calculator/', views.anniversary_and_milestone_calculator, name='anniversary_and_milestone_calculator'),
    path('semester_quarter_end_date_calculator/', views.semester_quarter_end_date_calculator, name='semester_quarter_end_date_calculator'),
    path('project_deadline_calculator/', views.project_deadline_calculator, name='project_deadline_calculator'),
    path('work_hours_net_pay_calculator/', views.work_hours_net_pay_calculator, name='work_hours_net_pay_calculator'),
    path('weekly_timesheet_pay_calculator/', views.weekly_timesheet_pay_calculator, name='weekly_timesheet_pay_calculator'),
    path('overtime_hours_pay_calculator/', views.overtime_hours_pay_calculator, name='overtime_hours_pay_calculator'),
    path('pay_period_date_calculator/', views.pay_period_date_calculator, name='pay_period_date_calculator'),
    path('sunrise_sunset_calculator/', views.sunrise_sunset_calculator, name='sunrise_sunset_calculator'),
    path('moon_phase_calendar_calculator/', views.moon_phase_calendar_calculator, name='moon_phase_calendar_calculator'),
    path('day_of_year_calculator/', views.day_of_year_calculator, name='day_of_year_calculator'),
    path('week_number_calculator/', views.week_number_calculator, name='week_number_calculator'),
    path('floating_holiday_date_calculator/', views.floating_holiday_date_calculator, name='floating_holiday_date_calculator'),
    path('tax_filing_deadline_calculator/', views.tax_filing_deadline_calculator, name='tax_filing_deadline_calculator'),
    path('vacation_day_accrual_calculator/', views.vacation_day_accrual_calculator, name='vacation_day_accrual_calculator'),
    path('lease_end_date_calculator/', views.lease_end_date_calculator, name='lease_end_date_calculator'),
    path('warranty_expiry_date_calculator/', views.warranty_expiry_date_calculator, name='warranty_expiry_date_calculator'),
    path('subscription_renewal_date_calculator/', views.subscription_renewal_date_calculator, name='subscription_renewal_date_calculator'),
    path('pregnancy_week_calculator/', views.pregnancy_week_calculator, name='pregnancy_week_calculator'),
    path('retirement_date_calculator/', views.retirement_date_calculator, name='retirement_date_calculator'),
    path('credit_card_payment_due_date_calculator/', views.credit_card_payment_due_date_calculator, name='credit_card_payment_due_date_calculator'),
    path('interest_accrual_date_calculator/', views.interest_accrual_date_calculator, name='interest_accrual_date_calculator'),
    path('historical_period_duration_calculator/', views.historical_period_duration_calculator, name='historical_period_duration_calculator'),
    path('seconds_to_time_converter/', views.seconds_to_time_converter, name='seconds_to_time_converter'),
    path('workday_time_calculator/', views.workday_time_calculator, name='workday_time_calculator'),
    path('half_and_double_time_calculator/', views.half_and_double_time_calculator, name='half_and_double_time_calculator'),
    path('chronological_age_calculator/', views.chronological_age_calculator, name='chronological_age_calculator'),
    path('galactic_time_converter/', views.galactic_time_converter, name='galactic_time_converter'),
    path('animal_age_calculator/', views.animal_age_calculator, name='animal_age_calculator'),
    path('countdown_to_specific_event/', views.countdown_to_specific_event, name='countdown_to_specific_event'),
    path('time_until_solar_eclipse_meteor_shower/', views.time_until_solar_eclipse_meteor_shower, name='time_until_solar_eclipse_meteor_shower'),
    path('airport_time_zone_finder/', views.airport_time_zone_finder, name='airport_time_zone_finder'),
    path('international_phone_call_time_planner/', views.international_phone_call_time_planner, name='international_phone_call_time_planner'),
    path('shipping_delivery_date_estimator/', views.shipping_delivery_date_estimator, name='shipping_delivery_date_estimator'),
    path('court_filing_deadline_calculator/', views.court_filing_deadline_calculator, name='court_filing_deadline_calculator'),
    path('statute_of_limitations_calculator/', views.statute_of_limitations_calculator, name='statute_of_limitations_calculator'),
    path('copyright_expiration_calculator/', views.copyright_expiration_calculator, name='copyright_expiration_calculator'),
    path('age_difference_calculator/', views.age_difference_calculator, name='age_difference_calculator'),
    path('half_birthday_calculator/', views.half_birthday_calculator, name='half_birthday_calculator'),
    path('seasons_start_end_calculator/', views.seasons_start_end_calculator, name='seasons_start_end_calculator'),

]