from django.urls import path
from . import views

urlpatterns = [
    path("", views.real_estate_dashboard, name="real_estate_dashboard"),
    path("days_on_market_calculator/", views.days_on_market_calculator, name="days_on_market_calculator"),
    path("mortgage_payment_calculator/", views.mortgage_payment_calculator, name="mortgage_payment_calculator"),
    path("piti_mortgage_calculator/", views.piti_mortgage_calculator, name="piti_mortgage_calculator"),
    path("mortgage_affordability_calculator/", views.mortgage_affordability_calculator, name="mortgage_affordability_calculator"),
    path("rent_vs_buy_calculator/", views.rent_vs_buy_calculator, name="rent_vs_buy_calculator"),
    path("mortgage_amortization_schedule_generator/", views.mortgage_amortization_schedule_generator, name="mortgage_amortization_schedule_generator"),
    path("extra_mortgage_payment_calculator/", views.extra_mortgage_payment_calculator, name="extra_mortgage_payment_calculator"),
    path("bi_weekly_portgage_payment_calculator/", views.bi_weekly_portgage_payment_calculator, name="bi_weekly_portgage_payment_calculator"),
    path("refinance_breakeven_calculator/", views.refinance_breakeven_calculator, name="refinance_breakeven_calculator"),
    path("dti_ratio_calculator/", views.dti_ratio_calculator, name="dti_ratio_calculator"),
    path("ltv_ratio_calculator/", views.ltv_ratio_calculator, name="ltv_ratio_calculator"),
    path("down_payment_calculator/", views.down_payment_calculator, name="down_payment_calculator"),
    path("pmi_calculator/", views.pmi_calculator, name="pmi_calculator"),
    path("fha_loan_calculator/", views.fha_loan_calculator, name="fha_loan_calculator"),
    path("va_loan_calculator/", views.va_loan_calculator, name="va_loan_calculator"),
    path("usda_loan_calculator/", views.usda_loan_calculator, name="usda_loan_calculator"),
    path("arm_calculator/", views.arm_calculator, name="arm_calculator"),
    path("closing_cost_calculator/", views.closing_cost_calculator, name="closing_cost_calculator"),
    path("seller_net_proceeds_calculator/", views.seller_net_proceeds_calculator, name="seller_net_proceeds_calculator"),
    path("rental_property_cash_flow_calculator/", views.rental_property_cash_flow_calculator, name="rental_property_cash_flow_calculator"),
    path("gross_rent_multiplier_calculator/", views.gross_rent_multiplier_calculator, name="gross_rent_multiplier_calculator"),
    path("capitalization_rate_calculator/", views.capitalization_rate_calculator, name="capitalization_rate_calculator"),
    path("cash_on_cash_return_calculator/", views.cash_on_cash_return_calculator, name="cash_on_cash_return_calculator"),
    path("total_return_on_investment_calculator/", views.total_return_on_investment_calculator, name="total_return_on_investment_calculator"),
    path("debt_service_coverage_ratio_calculator/", views.debt_service_coverage_ratio_calculator, name="debt_service_coverage_ratio_calculator"),
    path("rule_quickrental_analysis_calculator/", views.rule_quickrental_analysis_calculator, name="rule_quickrental_analysis_calculator"),
    path("rule_house_flipping_calculator/", views.rule_house_flipping_calculator, name="rule_house_flipping_calculator"),
    path("property_tax_calculator/", views.property_tax_calculator, name="property_tax_calculator"),
    path("homeowners_insurance_premium_estimator/", views.homeowners_insurance_premium_estimator, name="homeowners_insurance_premium_estimator"),
    path("home_appreciation_value_projection_calculator/", views.home_appreciation_value_projection_calculator, name="home_appreciation_value_projection_calculator"),
    path("price_per_square_foot_calculator/", views.price_per_square_foot_calculator, name="price_per_square_foot_calculator"),
    path("real_estate_agent_commission_calculator/", views.real_estate_agent_commission_calculator, name="real_estate_agent_commission_calculator"),
    path("land_lease_payment_calculator/", views.land_lease_payment_calculator, name="land_lease_payment_calculator"),
    path("piti_as_percentage_of_income_calculator/", views.piti_as_percentage_of_income_calculator, name="piti_as_percentage_of_income_calculator"),
    path("balloon_mortgage_calculator/", views.balloon_mortgage_calculator, name="balloon_mortgage_calculator"),
    path("construction_loan_interest_calculator/", views.construction_loan_interest_calculator, name="construction_loan_interest_calculator"),
    path("home_equity_loan_calculator/", views.home_equity_loan_calculator, name="home_equity_loan_calculator"),
    path("heloc_calculator/", views.heloc_calculator, name="heloc_calculator"),
    path("reverse_mortgage_calculator/", views.reverse_mortgage_calculator, name="reverse_mortgage_calculator"),
    path("buy_to_let_mortgage_calculator/", views.buy_to_let_mortgage_calculator, name="buy_to_let_mortgage_calculator"),
    path("hoa_fee_affordability_calculator/", views.hoa_fee_affordability_calculator, name="hoa_fee_affordability_calculator"),
    path("moving_cost_estimator/", views.moving_cost_estimator, name="moving_cost_estimator"),
    path("home_repair_budget_calculator/", views.home_repair_budget_calculator, name="home_repair_budget_calculator"),
    path("depreciation_calculator/", views.depreciation_calculator, name="depreciation_calculator"),
    path("exchange_calculator/", views.exchange_calculator, name="exchange_calculator"),
    path("annual_property_operating_data_calculator/", views.annual_property_operating_data_calculator, name="annual_property_operating_data_calculator"),
    path("net_operating_income_calculator/", views.net_operating_income_calculator, name="net_operating_income_calculator"),
    path("internal_rate_of_return_calculator/", views.internal_rate_of_return_calculator, name="internal_rate_of_return_calculator"),
    path("tenant_rent_to_income_ratio_calculator/", views.tenant_rent_to_income_ratio_calculator, name="tenant_rent_to_income_ratio_calculator"),

]