from django.urls import path
from . import views

urlpatterns = [
    path("", views.education_dashboard, name="education_dashboard"),
    path("gpa_calculator/", views.gpa_calculator, name="gpa_calculator"),
    path("final_grade_calculator/", views.final_grade_calculator, name="final_grade_calculator"),
    path("minimum_grade_required_calculator/", views.minimum_grade_required_calculator, name="minimum_grade_required_calculator"),
    path("high_school_gpa_calculator/", views.high_school_gpa_calculator, name="high_school_gpa_calculator"),
    path("college_gpa_calculator/", views.college_gpa_calculator, name="college_gpa_calculator"),
    path("student_loan_amortization_calculator/", views.student_loan_amortization_calculator, name="student_loan_amortization_calculator"),
    path("student_loan_refinance_savings_calculator/", views.student_loan_refinance_savings_calculator, name="student_loan_refinance_savings_calculator"),
    path("college_savings_plan_calculator/", views.college_savings_plan_calculator, name="college_savings_plan_calculator"),
    path("text_character_and_word_counter/", views.text_character_and_word_counter, name="text_character_and_word_counter"),
    path("text_reading_time_calculator/", views.text_reading_time_calculator, name="text_reading_time_calculator"),
    path("speech_and_presentation_length_calculator/", views.speech_and_presentation_length_calculator, name="speech_and_presentation_length_calculator"),
    path("words_per_minute_typing_speed_calculator/", views.words_per_minute_typing_speed_calculator, name="words_per_minute_typing_speed_calculator"),
    path("citation_generator/", views.citation_generator, name="citation_generator"),
    path("plagiarism_checker_score_estimator/", views.plagiarism_checker_score_estimator, name="plagiarism_checker_score_estimator"),
    path("semester_workload_calculator/", views.semester_workload_calculator, name="semester_workload_calculator"),
    path("weekly_study_time_planner_and_workload_organizer/", views.weekly_study_time_planner_and_workload_organizer, name="weekly_study_time_planner_and_workload_organizer"),
    path("class_schedule_conflict_checker/", views.class_schedule_conflict_checker, name="class_schedule_conflict_checker"),
    path("textbook_cost_calculator/", views.textbook_cost_calculator, name="textbook_cost_calculator"),
    path("student_monthly_budget_calculator/", views.student_monthly_budget_calculator, name="student_monthly_budget_calculator"),
    path("dorm_room_size_usable_area_calculator/", views.dorm_room_size_usable_area_calculator, name="dorm_room_size_usable_area_calculator"),
    path("scholarship_finder_match_score_calculator/", views.scholarship_finder_match_score_calculator, name="scholarship_finder_match_score_calculator"),
    path("act_to_sat_score_converter/", views.act_to_sat_score_converter, name="act_to_sat_score_converter"),
    path("percentile_rank_calculator/", views.percentile_rank_calculator, name="percentile_rank_calculator"),
    path("course_load_difficulty_calculator/", views.course_load_difficulty_calculator, name="course_load_difficulty_calculator"),
    path("graduation_timeline_planner/", views.graduation_timeline_planner, name="graduation_timeline_planner"),
    path("student_loan_forgiveness_eligibility_calculator/", views.student_loan_forgiveness_eligibility_calculator, name="student_loan_forgiveness_eligibility_calculator"),
    path("work_study_earnings_calculator/", views.work_study_earnings_calculator, name="work_study_earnings_calculator"),
    path("internship_stipend_budget_calculator/", views.internship_stipend_budget_calculator, name="internship_stipend_budget_calculator"),
    path("thesis_page_count_estimator/", views.thesis_page_count_estimator, name="thesis_page_count_estimator"),
    path("paragraph_structure_planner/", views.paragraph_structure_planner, name="paragraph_structure_planner"),
    path("essay_outline_generator/", views.essay_outline_generator, name="essay_outline_generator"),
    path("memorization_time_estimator/", views.memorization_time_estimator, name="memorization_time_estimator"),
    path("language_learning_fluency_timeline/", views.language_learning_fluency_timeline, name="language_learning_fluency_timeline"),
    path("project_deadline_calculator/", views.project_deadline_calculator, name="project_deadline_calculator"),
    path("group_project_contribution_tracker/", views.group_project_contribution_tracker, name="group_project_contribution_tracker"),
    path("presentation_slide_count_estimator/", views.presentation_slide_count_estimator, name="presentation_slide_count_estimator"),
    path("academic_probation_risk_calculator/", views.academic_probation_risk_calculator, name="academic_probation_risk_calculator"),
    path("major_change_impact_calculator/", views.major_change_impact_calculator, name="major_change_impact_calculator"),
    path("double_major_minor_time_calculator/", views.double_major_minor_time_calculator, name="double_major_minor_time_calculator"),
    path("study_abroad_cost_calculator/", views.study_abroad_cost_calculator, name="study_abroad_cost_calculator"),
    path("student_loan_debt_to_income_projector/", views.student_loan_debt_to_income_projector, name="student_loan_debt_to_income_projector"),
    path("teacher_gradebook_average_calculator/", views.teacher_gradebook_average_calculator, name="teacher_gradebook_average_calculator"),
    path("class_curve_grade_calculator/", views.class_curve_grade_calculator, name="class_curve_grade_calculator"),
    path("rubric_score_calculator/", views.rubric_score_calculator, name="rubric_score_calculator"),
    path("random_student_picker/", views.random_student_picker, name="random_student_picker"),
    path("semester_countdown_calculator/", views.semester_countdown_calculator, name="semester_countdown_calculator"),
    path("lecture_video_watch_time_calculator/", views.lecture_video_watch_time_calculator, name="lecture_video_watch_time_calculator"),
    path("online_course_progress_tracker/", views.online_course_progress_tracker, name="online_course_progress_tracker"),
    path("academic_paper_formatting_checker/", views.academic_paper_formatting_checker, name="academic_paper_formatting_checker"),
    path("lms_grade_calculator/", views.lms_grade_calculator, name="lms_grade_calculator"),

]