from django.urls import path
from . import views

urlpatterns = [
    path("", views.business_investment_home, name="business_investment_dashboard"),

    path('roi_calculator/', views.roi_calculator, name='roi_calculator'),
    path('compound_interest_calculator/', views.compound_interest_calculator, name='compound_interest_calculator'),
    path('net_present_value_calculator/', views.net_present_value_calculator, name='net_present_value_calculator'),
    path('internal_rate_of_return_calculator/', views.internal_rate_of_return_calculator, name='internal_rate_of_return_calculator'),
    path('payback_period_calculator/', views.payback_period_calculator, name='payback_period_calculator'),
    path('break_even_analysis_calculator/', views.break_even_analysis_calculator, name='break_even_analysis_calculator'),
    path('business_loan_calculator/', views.business_loan_calculator, name='business_loan_calculator'),
    path('sba_loan_calculator/', views.sba_loan_calculator, name='sba_loan_calculator'),
    path('gross_profit_margin_calculator/', views.gross_profit_margin_calculator, name='gross_profit_margin_calculator'),
    path('net_profit_margin_calculator/', views.net_profit_margin_calculator, name='net_profit_margin_calculator'),
    path('discount_calculator/', views.discount_calculator, name='discount_calculator'),
    path('customer_lifetime_value_calculator/', views.customer_lifetime_value_calculator, name='customer_lifetime_value_calculator'),
    path('customer_acquisition_cost_calculator/', views.customer_acquisition_cost_calculator, name='customer_acquisition_cost_calculator'),
    path('churn_rate_calculator/', views.churn_rate_calculator, name='churn_rate_calculator'),
    path('conversion_rate_calculator/', views.conversion_rate_calculator, name='conversion_rate_calculator'),
    path('return_on_ad_spend_calculator/', views.return_on_ad_spend_calculator, name='return_on_ad_spend_calculator'),
    path('through_rate_calculator/', views.through_rate_calculator, name='through_rate_calculator'),
    path('ebitda_calculator/', views.ebitda_calculator, name='ebitda_calculator'),
    path('working_capital_calculator/', views.working_capital_calculator, name='working_capital_calculator'),
    path('current_ratio_calculator/', views.current_ratio_calculator, name='current_ratio_calculator'),
    path('quick_ratio_calculator/', views.quick_ratio_calculator, name='quick_ratio_calculator'),
    path('debt_to_equity_ratio_calculator/', views.debt_to_equity_ratio_calculator, name='debt_to_equity_ratio_calculator'),
    path('inventory_turnover_calculator/', views.inventory_turnover_calculator, name='inventory_turnover_calculator'),
    path('days_sales_outstanding_calculator/', views.days_sales_outstanding_calculator, name='days_sales_outstanding_calculator'),
    path('burn_rate_and_runway_calculator/', views.burn_rate_and_runway_calculator, name='burn_rate_and_runway_calculator'),
    path('cash_runway_and_net_burn_calculator/', views.cash_runway_and_net_burn_calculator, name='cash_runway_and_net_burn_calculator'),
    path('financing_round_dilution_calculator/', views.financing_round_dilution_calculator, name='financing_round_dilution_calculator'),
    path('business_valuation_calculator/', views.business_valuation_calculator, name='business_valuation_calculator'),
    path('stock_total_return_calculator/', views.stock_total_return_calculator, name='stock_total_return_calculator'),
    path('dividend_yield_calculator/', views.dividend_yield_calculator, name='dividend_yield_calculator'),
    path('price_to_earnings_ratio_calculator/', views.price_to_earnings_ratio_calculator, name='price_to_earnings_ratio_calculator'),
    path('earnings_per_share_calculator/', views.earnings_per_share_calculator, name='earnings_per_share_calculator'),
    path('beta_coefficient_calculator/', views.beta_coefficient_calculator, name='beta_coefficient_calculator'),
    path('sharpe_ratio_calculator/', views.sharpe_ratio_calculator, name='sharpe_ratio_calculator'),
    path('compound_annual_growth_rate_calculator/', views.compound_annual_growth_rate_calculator, name='compound_annual_growth_rate_calculator'),
    path('dollar_cost_averaging_calculator/', views.dollar_cost_averaging_calculator, name='dollar_cost_averaging_calculator'),
    path('asset_allocation_calculator/', views.asset_allocation_calculator, name='asset_allocation_calculator'),
    path('portfolio_rebalancing_calculator/', views.portfolio_rebalancing_calculator, name='portfolio_rebalancing_calculator'),
    path('bond_yield_to_maturity_calculator/', views.bond_yield_to_maturity_calculator, name='bond_yield_to_maturity_calculator'),
    path('certificate_of_deposit_calculator/', views.certificate_of_deposit_calculator, name='certificate_of_deposit_calculator'),
    path('annuity_payout_calculator/', views.annuity_payout_calculator, name='annuity_payout_calculator'),
    path('retirement_calculator/', views.retirement_calculator, name='retirement_calculator'),
    path('roth_ira_cetirement_calculator/', views.roth_ira_cetirement_calculator, name='roth_ira_cetirement_calculator'),
    path('social_security_benefits_calculator/', views.social_security_benefits_calculator, name='social_security_benefits_calculator'),
    path('retirement_pension_forecaster/', views.retirement_pension_forecaster, name='retirement_pension_forecaster'),
    path('hsa_contribution_calculator/', views.hsa_contribution_calculator, name='hsa_contribution_calculator'),
    path('profit_and_loss_calculator/', views.profit_and_loss_calculator, name='profit_and_loss_calculator'),
    path('forex_pip_calculator/', views.forex_pip_calculator, name='forex_pip_calculator'),
    path('crypto_profit_calculator/', views.crypto_profit_calculator, name='crypto_profit_calculator'),

]