from django.urls import path
from . import views

urlpatterns = [
    path("", views.basic_calculator_home, name="basic_calculator_dashboard"),

    path('arithmetic/', views.arithmetic, name='arithmetic'),
    path('scientific_calculator/', views.scientific_calculator, name='scientific_calculator'),
    path('graphing_calculator/', views.graphing_calculator, name='graphing_calculator'),
    path('quadratic_solver/', views.quadratic_solver, name='quadratic_solver'),
    path('system_solver/', views.system_solver, name='system_solver'),
    path('matrix_calculator/', views.matrix_calculator, name='matrix_calculator'),
    path('derivative_calculator/', views.derivative_calculator, name='derivative_calculator'),
    path('integral_calculator/', views.integral_calculator, name='integral_calculator'),
    path('limit_calculator/', views.limit_calculator, name='limit_calculator'),
    path('prime_checker/', views.prime_checker, name='prime_checker'),
    path('factor_calculator/', views.factor_calculator, name='factor_calculator'),
    path('gcf_calculator/', views.gcf_calculator, name='gcf_calculator'),
    path('lcm_calculator/', views.lcm_calculator, name='lcm_calculator'),
    path('fraction_simplifier/', views.fraction_simplifier, name='fraction_simplifier'),
    path('fraction_to_decimal_converter/', views.fraction_to_decimal_converter, name='fraction_to_decimal_converter'),
    path('decimal_to_fraction_converter/', views.decimal_to_fraction_converter, name='decimal_to_fraction_converter'),
    path('percentage_calculator/', views.percentage_calculator, name='percentage_calculator'),
    path('percentage_change_calculator/', views.percentage_change_calculator, name='percentage_change_calculator'),
    path('ratio_calculator/', views.ratio_calculator, name='ratio_calculator'),
    path('proportion_calculator/', views.proportion_calculator, name='proportion_calculator'),
    path('standard_deviation_calculator/', views.standard_deviation_calculator, name='standard_deviation_calculator'),
    path('mean_median_mode_range_calculator/', views.mean_median_mode_range_calculator, name='mean_median_mode_range_calculator'),
    path('probability_calculator/', views.probabily_calculator, name='probabily_calculator'),
    path('permutation_calculator/', views.permutation_calculator, name='permutation_calculator'),
    path('combination_calculator/', views.combination_calculator, name='combination_calculator'),
    path('binomial_theorem_calculator/', views.binomial_theorem_calculator, name='binomial_theorem_calculator'),
    path('linear_regression_calculator/', views.linear_regression_calculator, name='linear_regression_calculator'),
    path('normal_distribution_calculator/', views.normal_distribution_calculator, name='normal_distribution_calculator'),
    path('pi_digit_finder/', views.pi_digit_finder, name='pi_digit_finder'),
    path('eulers_number_calculator/', views.eulers_number_calculator, name='eulers_number_calculator'),
    path('complex_number_calculator/', views.complex_number_calculator, name='complex_number_calculator'),
    path('vector_product_calculator/', views.vector_product_calculator, name='vector_product_calculator'),
    path('unit_vector_calculator/', views.unit_vector_calculator, name='unit_vector_calculator'),
    path('coordinate_converter/', views.coordinate_converter, name='coordinate_converter'),
    path('base_converter/', views.base_converter, name='base_converter'),
    path('scientific_notation_converter/', views.scientific_notation_converter, name='scientific_notation_converter'),
    path('significant_figures_counter/', views.significant_figures_counter, name='significant_figures_counter'),
    path('log_antilog_calculator/', views.log_antilog_calculator, name='log_antilog_calculator'),
    path('factorial_calculator/', views.factorial_calculator, name='factorial_calculator'),
    path('series_sum_calculator/', views.series_sum_calculator, name='series_sum_calculator'),
    path('pythagorean_calculator/', views.pythagorean_calculator, name='pythagorean_calculator'),
    path('area_volume_calculator/', views.area_volume_calculator, name='area_volume_calculator'),
    path('trig_identity_verifier/', views.trig_identity_verifier, name='trig_identity_verifier'),
    path('absolute_value_calculator/', views.absolute_value_calculator, name='absolute_value_calculator'),
    path('modulo_calculator/', views.modulo_calculator, name='modulo_calculator'),
    path('radical_simplifier/', views.radical_simplifier, name='radical_simplifier'),
    path('line_equation_calculator/', views.line_equation_calculator, name='line_equation_calculator'),
    path('truth_table_generator/', views.truth_table_generator, name='truth_table_generator'),
    path('boolean_algebra_calculator/', views.boolean_algebra_calculator, name='boolean_algebra_calculator'),
]
